Data manager spec
dc-lab/sky pull request #1
Opened 2019-12-24 01:29 UTC by BigRedEye

2019-12-24 01:37 UTC, BigRedEye commented
Про некоторые замечания:
* Q: Что значит "GET/GRPC" и "POST/GRPC"? Если имеется ввиду REST+gRPC, то зачем внутри REST?
 A: Некоторые ручки лаконичнее выразить доступными как и снаружи, так и изнутри. Например, загрузку файла в облако использует как и агент, так и пользователь.
* Q: Не понятно к чему Protobuf схемы в описании REST API? Надо привести примеры тел запроса-ответа на JSON.
 A: Насколько я понимаю, REST ортогонален используемому формату передачи. Учитывая специфику языков, кажется, что даже для публичного API удобнее использовать protobuf. Ну и, субъективно, protobuf строго лучше json как минимум из-за строгой схемы.
* Q: Почему бы вместо "file_id=" не включить id файла в URI? GET /files/file_id/info
A: Лично мне очень не нравится идея включать параметры запроса в путь, эти сущности как-то интуитивно разделяются, но сделал.
* Q: Агенту удобнее передавать сразу URI файлов для скачивания, чтобы он не думал как строить URI по id файла
A: Только агент знает про реальное состояние локальных файлов, так что не на каждый файл из StageInFiles агент пойдет скачивать его. Соответственно, кажется, что по id файла намного проще определять уже лежащие файлы.

2019-12-24 01:43 UTC, BigRedEye commented
По поводу оформления документации. Мне не нравится предложение из documenting-your-api: получается много бесполезного и сложного в написании текста, а действительно важные детали, такие как формат запроса, описываются крайне неудобно на каком-то очередном DSL.

Лично мне для понимания возможностей api практически всегда достаточно трех строк помимо текстового описания: uri, method, ссылка на proto-файл, может быть ещё в сложных случаях типы сообщений для запроса и ответа.

2019-12-24 01:44 UTC, BigRedEye commented on doc/data_manager.md
> +Внешнее API + дополнительные ручки:
Собственно, из-за этой детали хочется вообще все запросы описывать в protobuf.

2019-12-27 21:47 UTC, osukhoroslov requested changes
Замечания по внешнему API

2019-12-27 21:47 UTC, osukhoroslov commented on doc/data_manager.md
> ++ Optional
Надо описать кратко, что значит каждый параметр

2019-12-27 21:47 UTC, osukhoroslov commented on doc/data_manager.md
> +    * `blob=[bytes]`
Видимо предлагается передавать содержимое файла в кодировке Base64. Это не самый лучший вариант, так заметно увеличивает размер передаваемых данных и накладные расходы на обработку.

Лучше сначала загрузить файл отдельным запросом, а потом если надо выставить метаданные, ну или наоборот. Если хочется сразу убить двух зайцев, то можно воспользоваться multipart-форматом. См. для примера:
- https://developers.google.com/drive/api/v3/manage-uploads
- https://cloud.google.com/storage/docs/json_api/v1/how-tos/upload
- https://yandex.ru/dev/disk/api/reference/upload-docpage/ (загрузка в два шага)
- https://cloud.yandex.ru/docs/storage/s3/api-ref/object/upload (метаданные в заголовке - не очень)

2019-12-27 21:47 UTC, osukhoroslov commented on doc/data_manager.md
> +`/upload`
```suggestion
`/files`
```

2019-12-27 21:47 UTC, osukhoroslov commented on doc/data_manager.md
> +curl https://sky.io/api/file/upload -X POST --data '{
```suggestion
curl https://sky.io/api/files -X POST --data '{
```

2019-12-27 21:47 UTC, osukhoroslov commented on doc/data_manager.md
> ++ `/download/:file_id`
```suggestion
+ `/file/:file_id/data`
```

2019-12-27 21:47 UTC, osukhoroslov commented on doc/data_manager.md
> +    "contents": [bytes],
Аналогичное замечание про передачу содержимого файла в Base64. Лучше передать файл просто в теле ответа в родном Content-Type, а имя файла в заголовке Content-Disposition.

2019-12-27 21:47 UTC, osukhoroslov commented on doc/data_manager.md
> +curl https://sky.io/api/files/dc4eec6e-4e34-49a7-8fe8-8e19d5bfb8a4/download
```suggestion
curl https://sky.io/api/files/dc4eec6e-4e34-49a7-8fe8-8e19d5bfb8a4/data
```

2019-12-27 21:47 UTC, osukhoroslov commented on doc/data_manager.md
> ++ `/download/:file_id`
```suggestion
+ `/files/:file_id/info`
```

2019-12-27 21:47 UTC, osukhoroslov commented on doc/data_manager.md
> ++ `/download/:job_id/:filename`
Это лишнее?

2019-12-27 21:47 UTC, osukhoroslov commented on doc/data_manager.md
> +curl https://sky.io/api/dc4eec6e-4e34-49a7-8fe8-8e19d5bfb8a4/info
```suggestion
curl https://sky.io/api/files/dc4eec6e-4e34-49a7-8fe8-8e19d5bfb8a4/info
```

2019-12-27 21:47 UTC, osukhoroslov commented on doc/data_manager.md
> +Внешнее API + дополнительные ручки:
Можно попробовать (см. мое сообщение в чате про варианты). Но загрузку/выгрузку файлов на protobuf в любом случае не перенесешь.

2019-12-27 22:16 UTC, osukhoroslov commented
>     * Лично мне очень не нравится идея включать параметры запроса в путь, эти сущности как-то интуитивно разделяются, но сделал.

Почитайте https://cloud.google.com/apis/design/

2020-02-24 13:55 UTC, osukhoroslov requested changes

2020-05-02 23:00 UTC, merged

2020-05-02 23:16 UTC, BigRedEye commented
Тестовая инсталляция доступна по адресу https://sky.sskvor.dev/