Created spec
dc-lab/sky pull request #2
Opened 2019-12-30 08:53 UTC by ilya-pauzner

2020-01-10 21:14 UTC, osukhoroslov reviewed
URI сейчас совсем не похожи не REST. Задания - это коллекция ресурсов в терминах REST. У каждого ресурса должен быть свой уникальный URI. Операции над ресурсом должны быть привязаны к этому URI. Добавление нового ресурса делается как POST на корневом URI коллекции.

2020-01-10 21:14 UTC, osukhoroslov commented on doc/job_manager.md
> +    "answer_id": [uuid],
Хорошо бы также возвращать здесь параметры задания (команду, входные файлы и т.д.), чтобы была вся необходимая информация.

2020-01-10 21:14 UTC, osukhoroslov commented on doc/job_manager.md
> +##### Внешнее API
```suggestion
##### Внешний API
```
API - интерфейс - он

2020-01-10 21:14 UTC, osukhoroslov commented on doc/job_manager.md
> +#### Внешнее API
```suggestion
#### Внешний API
```

2020-01-20 06:26 UTC, ilya-pauzner commented on doc/job_manager.md
> ++ **Code**: `400 / 403`
Выкинул 403, описание кодов будет.

2020-01-20 06:26 UTC, ilya-pauzner commented on doc/job_manager.md
> +    "job_ids" : [array of uids]
Не очень понятно пока какую информацию возвращать.

2020-01-20 06:27 UTC, ilya-pauzner commented on doc/job_manager.md
> +    "answer_id": [uuid],
> 
> 
> Непонятно что такое answer_id. Добавьте пояснения к каждому полю что оно значит.

Добавил про answer_id, возврат параметров задания будет.

2020-01-24 15:23 UTC, osukhoroslov requested changes

2020-01-24 15:23 UTC, osukhoroslov commented on doc/job_manager.md
> +	* `output_files=[array of string]`
Поправить отступ

2020-01-24 15:23 UTC, osukhoroslov commented on doc/job_manager.md
> +    * `binary=[uuid]`
binary можно передать как один из входных файлов, предлагаю убрать

2020-01-24 15:23 UTC, osukhoroslov commented on doc/job_manager.md
> +    "job_ids" : [array of uids]
Ту же, что в запросе состояния отдельного задания

2020-01-24 15:23 UTC, osukhoroslov commented on doc/job_manager.md
> ++ `/list_jobs`
```suggestion
+ `/jobs`
```

2020-01-24 15:23 UTC, osukhoroslov commented on doc/job_manager.md
> +    "answer_id": [list of uuids],
Предлагаю для ясности переименовать в results

2020-01-24 15:23 UTC, osukhoroslov commented on doc/job_manager.md
> +###### Success Response
Надо также возвращать здесь параметры задания (команду, входные файлы и т.д.), чтобы была вся необходимая информация.

2020-01-24 15:23 UTC, osukhoroslov commented on doc/job_manager.md
> +    * `ttl=[uint64]`
Описать что такое ttl?

2020-01-24 15:23 UTC, osukhoroslov commented on doc/job_manager.md
> +    * `input_files=[array of uuid]`
Когда надо запустить task, то кроме входных файлов может понадобиться информация о том, куда (относительно директории таска) и с каким именем какой файл разместить перед запуском таска. То есть удобнее задавать input_files как массив из структур (uuid, path).

2020-01-24 15:23 UTC, osukhoroslov commented on doc/job_manager.md
> +###### Data Params
Надо не забывать, что job может включать в себя несколько tasks. Для начала мы рассматриваем случай с одной задачей в задании, но лучше сразу явно прописать в запросе тип задания в поле type. Пусть для простейшего случая тип будет `simple`. И также надо завести поле `tasks` и всю информацию про задачу (command, input/output_files) надо перенести туда.

2020-02-10 06:01 UTC, ilya-pauzner commented on doc/job_manager.md
> +    * `binary=[uuid]`
Требует дополнительной конвенции (например, передавать первым файлом), но это не проблема. Поменял.

2020-02-14 15:19 UTC, osukhoroslov requested changes

2020-02-14 15:19 UTC, osukhoroslov commented on doc/job_manager.md
> +ttl = время жизни задания, по истечению которого оно будет принудительно завершено.
почему тогда выше у каждого таска свой ttl?

2020-02-14 15:19 UTC, osukhoroslov commented on doc/job_manager.md
> +    "tasks": {
Неправильный формат запроса, tasks - это массив

2020-02-14 15:19 UTC, osukhoroslov commented on doc/job_manager.md
> ++ **Comments**:
Добавьте сюда пояснения про поля задачи (task)

2020-02-14 15:19 UTC, osukhoroslov commented on doc/job_manager.md
> ++ **Comments**:
добавить state, его возможные значения (например, SUBMITTED, SCHEDULED, RUNNING, DONE, FAILED...)

2020-02-14 15:19 UTC, osukhoroslov commented on doc/job_manager.md
> +    "job_ids" : [array of uids]
Что с этим замечанием?

2020-02-24 10:55 UTC, osukhoroslov requested changes

2020-02-24 10:55 UTC, osukhoroslov commented on doc/job_manager.md
> ++ `GET /list_jobs` --- получение списка заданий.
```suggestion
+ `GET /jobs` --- получение списка заданий.
```

2020-02-24 10:55 UTC, osukhoroslov commented on doc/job_manager.md
> +curl https://sky.io/api/jobs -X POST --data '{
- добавить type=simple
- оставить только одну задачу
- в command не использовать пайпы и перенаправления потоков (это будет сложно поддержать в агенте)
- добавить в задачу input_files
- в output_files можно сделать соглашение, что файлы stdout и stderr соответствуют выводам стандартных потоков команды

2020-02-24 10:55 UTC, osukhoroslov commented on doc/job_manager.md
> +ttl = время жизни задачи (таска), по истечению которого оно будет принудительно завершено.
```suggestion
time_limit = лимит на время выполнения задачи, по истечению которого она будет принудительно завершена.
```
Термин TTL принят в сетях, может быть сразу не понятно для пользователя что это, лучше переименовать.

2020-05-20 00:07 UTC, merged